sudo: required
language: java
jdk:
  - oraclejdk11
services:
  - docker
script:
  - bash build.sh
after_success:
  - git add -f build/libs/application.jar  
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "account"
  env: "account-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-693697407816"
  bucket_path: "account"
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^release\/.*$	  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
